---
# Source: myblog/templates/networkpolicies.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: myblog
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
# Source: myblog/templates/networkpolicies.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: myblog
  namespace: myblog
spec:
  podSelector:
    matchLabels:
      app: myblog
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: asm-ingress
      podSelector:
        matchLabels:
          asm: ingressgateway
    ports:
     - port: 8080
       protocol: TCP
  egress:
  - {}
---
# Source: myblog/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myblog
  namespace: myblog
---
# Source: myblog/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myblog
  namespace: myblog
spec:
  type: ClusterIP
  selector:
    app: myblog
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
# Source: myblog/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog
  namespace: myblog
  labels:
    app: myblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog
  template:
    metadata:
      labels:
        app: myblog
    spec:
      serviceAccountName: myblog
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: myblog
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
          image: northamerica-northeast1-docker.pkg.dev/acm-workshop-216-tenant/containers/myblog:0.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 5m
              memory: 6Mi
            limits:
              cpu: 15m
              memory: 122Mi
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            tcpSocket:
              port: 8080
          volumeMounts:
          - mountPath: /tmp
            name: tmp
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - emptyDir: {}
        name: tmp
---
# Source: myblog/templates/authorizationpolicies.yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: myblog
  namespace: myblog
spec:
  selector:
    matchLabels:
      app: myblog
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/asm-ingress/sa/asm-ingressgateway
    to:
    - operation:
        methods:
        - GET
        ports:
        - "8080"
---
# Source: myblog/templates/sidecar.yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: myblog
spec:
  workloadSelector:
    labels:
      app: myblog
  egress:
  - hosts:
    - "istio-system/*"
---
# Source: myblog/templates/virtualservice.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myblog
  namespace: myblog
spec:
  hosts:
    - alwaysupalwayson.com
  gateways:
  - asm-ingress/asm-ingressgateway
  http:
  - route:
    - destination:
        host: myblog
        port:
          number: 80
