steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', '--recurse-submodules', 'https://github.com/${_REPO_OWNER}/${_APP_NAME}']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', '${_CONTAINER_REGISTRY_NAME}/${_APP_NAME}:$SHORT_SHA', '--build-arg', 'ALPINE_BASE_IMAGE=${_CONTAINER_REGISTRY_NAME}/alpine', '--build-arg', 'NGINX_BASE_IMAGE=${_CONTAINER_REGISTRY_NAME}/nginx-unprivileged', '${_APP_NAME}/.']
- name: gcr.io/cloud-builders/docker
  args: ['run', '-d', -p 8080:8080', '${_CONTAINER_REGISTRY_NAME}/${_APP_NAME}:$SHORT_SHA']
- name: gcr.io/cloud-builders/docker
  args: ['push', '${_CONTAINER_REGISTRY_NAME}/${_APP_NAME}:$SHORT_SHA']
- name: 'ubuntu'
  args: ['bash','-c','sed -i "s,CONTAINER_IMAGE_NAME,${_CONTAINER_REGISTRY_NAME}/${_APP_NAME}:$SHORT_SHA,g" k8s/deployment.yaml']
- name: gcr.io/cloud-builders/kubectl
  args: ['apply', '-f', 'k8s/namespace.yaml', '-f', 'k8s/', '-n', 'myblog']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
substitutions:
    _APP_NAME: myblog
    _REPO_OWNER: mathieu-benoit
    _CONTAINER_REGISTRY_NAME: SUBSTITUTE_ME
    _CLOUDSDK_COMPUTE_ZONE: us-east4-a
    _CLOUDSDK_CONTAINER_CLUSTER: SUBSTITUTE_ME
    _CLOUDSDK_CORE_PROJECT: SUBSTITUTE_ME
